// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

namespace WebApi.Migrations
{
    public partial class LocationsMoniker : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "IX_Locations_Title",
                table: "Locations");

            migrationBuilder.AddColumn<string>(
                name: "Moniker",
                table: "Locations",
                nullable: true);

            migrationBuilder.CreateIndex(
                name: "IX_Locations_Moniker",
                table: "Locations",
                column: "Moniker",
                unique: true);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "IX_Locations_Moniker",
                table: "Locations");

            migrationBuilder.DropColumn(
                name: "Moniker",
                table: "Locations");

            migrationBuilder.CreateIndex(
                name: "IX_Locations_Title",
                table: "Locations",
                column: "Title",
                unique: true);
        }
    }
}
