// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

namespace WebApi.Migrations
{
    public partial class PrototypeSetsTituls : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.RenameColumn(
                name: "ProductGroup",
                table: "PrototypeSets",
                newName: "ProductGroupTitle");

            migrationBuilder.RenameColumn(
                name: "Outlet",
                table: "PrototypeSets",
                newName: "ProductGroupCode");

            migrationBuilder.RenameColumn(
                name: "Location",
                table: "PrototypeSets",
                newName: "OutletTitle");

            migrationBuilder.RenameColumn(
                name: "GateLevel",
                table: "PrototypeSets",
                newName: "OutletCode");

            migrationBuilder.RenameColumn(
                name: "EvidenceYear",
                table: "PrototypeSets",
                newName: "LocationTitle");

            migrationBuilder.AddColumn<string>(
                name: "EvidenceYearCode",
                table: "PrototypeSets",
                type: "text",
                nullable: true);

            migrationBuilder.AddColumn<int>(
                name: "EvidenceYearTitle",
                table: "PrototypeSets",
                type: "integer",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.AddColumn<string>(
                name: "GateLevelCode",
                table: "PrototypeSets",
                type: "text",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "GateLevelTitle",
                table: "PrototypeSets",
                type: "text",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "LocationCode",
                table: "PrototypeSets",
                type: "text",
                nullable: true);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "EvidenceYearCode",
                table: "PrototypeSets");

            migrationBuilder.DropColumn(
                name: "EvidenceYearTitle",
                table: "PrototypeSets");

            migrationBuilder.DropColumn(
                name: "GateLevelCode",
                table: "PrototypeSets");

            migrationBuilder.DropColumn(
                name: "GateLevelTitle",
                table: "PrototypeSets");

            migrationBuilder.DropColumn(
                name: "LocationCode",
                table: "PrototypeSets");

            migrationBuilder.RenameColumn(
                name: "ProductGroupTitle",
                table: "PrototypeSets",
                newName: "ProductGroup");

            migrationBuilder.RenameColumn(
                name: "ProductGroupCode",
                table: "PrototypeSets",
                newName: "Outlet");

            migrationBuilder.RenameColumn(
                name: "OutletTitle",
                table: "PrototypeSets",
                newName: "Location");

            migrationBuilder.RenameColumn(
                name: "OutletCode",
                table: "PrototypeSets",
                newName: "GateLevel");

            migrationBuilder.RenameColumn(
                name: "LocationTitle",
                table: "PrototypeSets",
                newName: "EvidenceYear");
        }
    }
}
