// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace WebApi.Migrations
{
    public partial class AddPrototypeSets : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "PrototypeSets",
                columns: table => new
                {
                    Id = table.Column<int>(nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    Outlet = table.Column<string>(nullable: true),
                    ProductGroup = table.Column<string>(nullable: true),
                    GateLevel = table.Column<string>(nullable: true),
                    EvidenceYear = table.Column<string>(nullable: true),
                    Location = table.Column<string>(nullable: true),
                    SetIdentifier = table.Column<string>(nullable: true),
                    ProjectId = table.Column<int>(nullable: false),
                    CreatedAt = table.Column<DateTimeOffset>(nullable: true),
                    CreateById = table.Column<int>(nullable: false),
                    ModifiedAt = table.Column<DateTimeOffset>(nullable: true),
                    ModifiedById = table.Column<int>(nullable: false),
                    DeletedAt = table.Column<DateTimeOffset>(nullable: true),
                    DeletedById = table.Column<int>(nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_PrototypeSets", x => x.Id);
                    table.ForeignKey(
                        name: "FK_PrototypeSets_Users_CreateById",
                        column: x => x.CreateById,
                        principalTable: "Users",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_PrototypeSets_Users_DeletedById",
                        column: x => x.DeletedById,
                        principalTable: "Users",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_PrototypeSets_Users_ModifiedById",
                        column: x => x.ModifiedById,
                        principalTable: "Users",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "IX_PrototypeSets_CreateById",
                table: "PrototypeSets",
                column: "CreateById");

            migrationBuilder.CreateIndex(
                name: "IX_PrototypeSets_DeletedById",
                table: "PrototypeSets",
                column: "DeletedById");

            migrationBuilder.CreateIndex(
                name: "IX_PrototypeSets_ModifiedById",
                table: "PrototypeSets",
                column: "ModifiedById");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "PrototypeSets");
        }
    }
}
