// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

namespace WebApi.Migrations
{
    public partial class PartsMoniker : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "IX_Parts_Code",
                table: "Parts");

            migrationBuilder.DropIndex(
                name: "IX_Parts_Title",
                table: "Parts");

            migrationBuilder.AddColumn<string>(
                name: "Moniker",
                table: "Parts",
                nullable: true);

            migrationBuilder.CreateIndex(
                name: "IX_Parts_Moniker",
                table: "Parts",
                column: "Moniker",
                unique: true);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "IX_Parts_Moniker",
                table: "Parts");

            migrationBuilder.DropColumn(
                name: "Moniker",
                table: "Parts");

            migrationBuilder.CreateIndex(
                name: "IX_Parts_Code",
                table: "Parts",
                column: "Code",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_Parts_Title",
                table: "Parts",
                column: "Title",
                unique: true);
        }
    }
}
