// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

namespace WebApi.Migrations
{
    public partial class PrototypesCreatedBy : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_Prototypes_Users_CreateById",
                table: "Prototypes");

            migrationBuilder.RenameColumn(
                name: "CreateById",
                table: "Prototypes",
                newName: "CreatedById");

            migrationBuilder.RenameIndex(
                name: "IX_Prototypes_CreateById",
                table: "Prototypes",
                newName: "IX_Prototypes_CreatedById");

            migrationBuilder.AddForeignKey(
                name: "FK_Prototypes_Users_CreatedById",
                table: "Prototypes",
                column: "CreatedById",
                principalTable: "Users",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_Prototypes_Users_CreatedById",
                table: "Prototypes");

            migrationBuilder.RenameColumn(
                name: "CreatedById",
                table: "Prototypes",
                newName: "CreateById");

            migrationBuilder.RenameIndex(
                name: "IX_Prototypes_CreatedById",
                table: "Prototypes",
                newName: "IX_Prototypes_CreateById");

            migrationBuilder.AddForeignKey(
                name: "FK_Prototypes_Users_CreateById",
                table: "Prototypes",
                column: "CreateById",
                principalTable: "Users",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);
        }
    }
}
