// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

namespace WebApi.Migrations
{
    public partial class PrototypeSetsCreatedBy : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_PrototypeSets_Users_CreateById",
                table: "PrototypeSets");

            migrationBuilder.RenameColumn(
                name: "CreateById",
                table: "PrototypeSets",
                newName: "CreatedById");

            migrationBuilder.RenameIndex(
                name: "IX_PrototypeSets_CreateById",
                table: "PrototypeSets",
                newName: "IX_PrototypeSets_CreatedById");

            migrationBuilder.AddForeignKey(
                name: "FK_PrototypeSets_Users_CreatedById",
                table: "PrototypeSets",
                column: "CreatedById",
                principalTable: "Users",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_PrototypeSets_Users_CreatedById",
                table: "PrototypeSets");

            migrationBuilder.RenameColumn(
                name: "CreatedById",
                table: "PrototypeSets",
                newName: "CreateById");

            migrationBuilder.RenameIndex(
                name: "IX_PrototypeSets_CreatedById",
                table: "PrototypeSets",
                newName: "IX_PrototypeSets_CreateById");

            migrationBuilder.AddForeignKey(
                name: "FK_PrototypeSets_Users_CreateById",
                table: "PrototypeSets",
                column: "CreateById",
                principalTable: "Users",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);
        }
    }
}
