// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

namespace WebApi.Migrations
{
    public partial class AddPartToComponentPartRelation : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "PartToComponentPartRelations",
                columns: table => new
                {
                    PartId = table.Column<int>(type: "integer", nullable: false),
                    ComponentPartId = table.Column<int>(type: "integer", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_PartToComponentPartRelations", x => new { x.PartId, x.ComponentPartId });
                    table.ForeignKey(
                        name: "FK_PartToComponentPartRelations_Parts_ComponentPartId",
                        column: x => x.ComponentPartId,
                        principalTable: "Parts",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_PartToComponentPartRelations_Parts_PartId",
                        column: x => x.PartId,
                        principalTable: "Parts",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateIndex(
                name: "IX_PartToComponentPartRelations_ComponentPartId",
                table: "PartToComponentPartRelations",
                column: "ComponentPartId");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "PartToComponentPartRelations");
        }
    }
}
