// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

namespace WebApi.Migrations
{
    public partial class PackagesCreatedBy : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_PrototypesPackages_Users_CreateById",
                table: "PrototypesPackages");

            migrationBuilder.RenameColumn(
                name: "CreateById",
                table: "PrototypesPackages",
                newName: "CreatedById");

            migrationBuilder.RenameIndex(
                name: "IX_PrototypesPackages_CreateById",
                table: "PrototypesPackages",
                newName: "IX_PrototypesPackages_CreatedById");

            migrationBuilder.AddForeignKey(
                name: "FK_PrototypesPackages_Users_CreatedById",
                table: "PrototypesPackages",
                column: "CreatedById",
                principalTable: "Users",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_PrototypesPackages_Users_CreatedById",
                table: "PrototypesPackages");

            migrationBuilder.RenameColumn(
                name: "CreatedById",
                table: "PrototypesPackages",
                newName: "CreateById");

            migrationBuilder.RenameIndex(
                name: "IX_PrototypesPackages_CreatedById",
                table: "PrototypesPackages",
                newName: "IX_PrototypesPackages_CreateById");

            migrationBuilder.AddForeignKey(
                name: "FK_PrototypesPackages_Users_CreateById",
                table: "PrototypesPackages",
                column: "CreateById",
                principalTable: "Users",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);
        }
    }
}
